### ISSUE TITLE
Problem ?

### ISSUE THREAD

**Issue by echoffs** [blazeeboy/RubyScripts#2]
C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=
1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Fara
day::SSLError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from C:/Ruby22-x64/lib/ruby/2.2.0/net/http.rb:1133:in `get'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ad
apter/net_http.rb:80:in `perform_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ad
apter/net_http.rb:40:in `block in call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ad
apter/net_http.rb:87:in `with_net_http_connection'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ad
apter/net_http.rb:32:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/re
quest/url_encoded.rb:15:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/re
quest/multipart.rb:14:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/ra
ck_builder.rb:139:in `build_response'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/co
nnection.rb:377:in `run_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/co
nnection.rb:140:in `get'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/koala-2.2.0/lib/koala/http_s
ervice.rb:113:in `make_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/koala-2.2.0/lib/koala.rb:64:
in `make_request'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/koala-2.2.0/lib/koala/api.rb
:74:in `api'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/koala-2.2.0/lib/koala/api/gr
aph_api.rb:513:in `graph_call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/koala-2.2.0/lib/koala/api/gr
aph_api.rb:115:in `get_connection'
        from C:/Users/Master/Desktop/fbrb.rb:12:in `<main>'

Using proper oauth generated code.

**Comment by blazeeboy** [comment]
can you describe more how do you get this error?, what is the command you're trying to execute, what is teh script your using?
